---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}

```

## Clothing observed in public

This report summarises observations of clothing worn by individuals. Each entry represents one observed person.

```{r}
library(tidyverse)

logged_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTfFXPbCzJUlKjqNKs_BKGkpjzNITAU4JLc0SxXf8yGaOQ7TrWk6_aQPZVexX46cHnCdKKXUi8TmdO7/pub?output=csv")

latest_data <- logged_data %>%
  rename(
    top_type = `What type of top is the person wearing?`,
    colour = `What colour category is the top?`,
    age = `Estimate age of the person`
  ) 
```

### Summary

The average estimated age observed was `r round(mean(latest_data$age),1)` years.

A total of `r length(latest_data$age)` individuals were observed.

```{r}
ggplot(latest_data, aes(x = top_type, fill = top_type)) +
  geom_bar() +
  theme_minimal()
```

```{r}
ggplot(latest_data, aes(x = colour, fill = colour)) +
  geom_bar() +
  theme_minimal()
```